# Generated by Django 3.1.7 on 2021-04-02 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products_site_app', '0002_auto_20210331_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='picture',
            field=models.ImageField(blank=True, default='default_img.png', null=True, upload_to='static/media/'),
        ),
        migrations.CreateModel(
            name='Cart_products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products_site_app.products')),
            ],
        ),
    ]
