# Generated by Django 3.1.7 on 2021-04-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_site_app', '0003_auto_20210402_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_products',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
