# Generated by Django 3.1.7 on 2021-04-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_site_app', '0004_auto_20210402_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_products',
            name='name',
            field=models.CharField(default='no-name', max_length=100),
        ),
    ]
